[Server]
host = 0.0.0.0
port = 5000
debug = True
environment = development
timezone = Asia/Kolkata

[POSTGRES] # For Postgres change environment to "production" and debug to "False"
host = localhost
port = 5432
database = bridge_db
username = postgres
password = secret

[SQLITE] # For SQLite change environment to "development" and debug to "True"
path = instance
database = bridge_app.db

[UI]
theme = glass
colormode = auto
date_format = DD/MM/YYYY HH:mm:ss

[OPENTELEMETRY]
# Set enabled to true when your Zabbix or Jaeger server is running to avoid ConnectionRefused errors
enabled = false
otlp_endpoint = http://localhost:4318/v1/traces

[Logging]
log_dir = logs
rotation = daily
backup_count = 30

[RetryQueue]
retention_minutes = 60

[Swagger]
refresh_interval = 1
refresh_unit = hours
